name: Deploy to GitHub Pages
# Run workflow on every push to the master branch
on:
    push:
      branches: [ master ]
jobs:
    deploy-to-github-pages:
        # use ubuntu-latest image to run steps on
        runs-on: ubuntu-latest
        steps:
            # uses GitHub's checkout action to checkout code form the Blazor branch
            - uses: actions/checkout@v4

            # fix js interop paths
            - name: Fix JS Filepaths
              run: |
                sed -i 's|/js/LocalStorageAccessor.js|/LTSaveEd/js/LocalStorageAccessor.js|' ./Models/JSWrapper/LocalStorageAccessor.cs
                sed -i 's|/js/FileHandler.js|/LTSaveEd/js/FileHandler.js|' ./Models/JSWrapper/FileHandler.cs
          
          # sets up .NET Core SDK 3.1
            - name: Setup .NET Core SDK
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: 8.0

            # publishes Blazor project to the release-folder
            - name: Publish .NET Core Project
              run: dotnet publish LTSaveEd.csproj -c Release -o release --nologo

            # changes the base-tag in index.html from '/' to 'LTSaveEd' to match GitHub Pages repository subdirectory
            - name: Change base-tag in index.html from / to LTSaveEd
              run: sed -i 's/<base href="\/" \/>/<base href="\/LTSaveEd\/" \/>/g' release/wwwroot/index.html

            # copy index.html to 404.html to serve the same file when a file is not found
            - name: copy index.html to 404.html
              run: cp release/wwwroot/index.html release/wwwroot/404.html

            # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
            - name: Add .nojekyll file
              run: touch release/wwwroot/.nojekyll
            - name: Commit wwwroot to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                BRANCH: gh-pages
                FOLDER: release/wwwroot
